title: Tanumbotics
description: Developing an agricultural drone for monitoring analysis of crop health and infestation. A Jollibee Farmer Entrepreneurship Program (FEP) project
show_downloads: false
theme: jekyll-theme-cayman
